[package]
name = "metar"
version = "0.7.7"
authors = ["Lily Hopkins <lily@hpkns.uk>"]
edition = "2021"
description = "A fast METAR parsing library in pure Rust"
license = "MIT"
homepage = "https://github.com/lilopkins/metar-rs"
repository = "https://github.com/lilopkins/metar-rs"
readme = "README.md"

[dependencies]
pest = "2.7.4"
pest_derive = "2.7.4"

[dev-dependencies]
anyhow = "1.0"
async-trait = "0.1"
cucumber = "0.20.0"
futures = "0.3"

[[test]]
name = "cucumber"
harness = false
