[package]
name = "metar"
version = "0.2.0"
authors = ["Lily Hopkins <bsalarius@gmail.com>"]
edition = "2018"
description = "METAR parsing library for Rust"
license = "MIT"
homepage = "https://github.com/lilopkins/metar-rs"
repository = "https://github.com/lilopkins/metar-rs"

[dependencies]
regex = "1"
