[package]
name = "metar"
version = "0.3.0"
authors = ["Lily Hopkins <bsalarius@gmail.com>"]
edition = "2018"
description = "A zero-dependency METAR parsing library in pure Rust"
license = "MIT"
homepage = "https://github.com/lilopkins/metar-rs"
repository = "https://github.com/lilopkins/metar-rs"
readme = "README.md"

[dependencies]
