[package]
name = "metar"
version = "0.5.0"
authors = ["Lily Hopkins <bsalarius@gmail.com>"]
edition = "2021"
description = "A fast METAR parsing library in pure Rust"
license = "MIT"
homepage = "https://github.com/lilopkins/metar-rs"
repository = "https://github.com/lilopkins/metar-rs"
readme = "README.md"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"

[dev-dependencies]
anyhow = "1.0.57"
